services:
  - type: web
    name: spotify2mp3-web
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: OUTPUT_DIR
        value: /data/downloads
      - key: YT_GEO
        value: US
      - key: YT_SOURCE_ADDRESS
        value: 0.0.0.0
      - key: YT_CLIENTS
        value: android,web_embedded,tvhtml5
      - key: RATE_LIMIT
        value: 800K
      - key: YT_PROXY
        value: ""
      - key: SLEEP_MIN
        value: "2.5"
      - key: SLEEP_MAX
        value: "6.0"
      - key: YT_UA_LIST
        value: |
          Mozilla/5.0 (Linux; Android 12; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Mobile Safari/537.36||Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1||Mozilla/5.0 (Chromium, like Gecko) TV Safari/537.36 YouTube/Android TV
      - key: INVIDIOUS_INSTANCE
        value: ""
      - key: ENABLE_SOUNDCLOUD_FALLBACK
        value: "true"
    healthCheckPath: /api/ffmpeg
    disk:
      name: s2mp3-data
      mountPath: /data
      sizeGB: 5
